/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import model.Person;
import model.HomeAddress;
import model.LocalAddress;
import model.BankAccount;

/**
 *
 * @author vedanarayananshrirangesh
 */
public class MainJFrame extends javax.swing.JFrame {
    Person person = new Person();
    HomeAddress homeAddress = new HomeAddress();
    LocalAddress localAddress = new LocalAddress();
    BankAccount bankAccount = new BankAccount();

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelButtons = new javax.swing.JPanel();
        btnCreatePerson = new javax.swing.JButton();
        btnViewPerson = new javax.swing.JButton();
        btnCreateHomeAddress = new javax.swing.JButton();
        btnViewHomeAddress = new javax.swing.JButton();
        btnCreateLocalAddress = new javax.swing.JButton();
        btnViewLocalAddress = new javax.swing.JButton();
        btnCreateBankAccount = new javax.swing.JButton();
        btnViewBankAccount = new javax.swing.JButton();
        panelDisplay = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnViewPerson.setText("View Person");
        btnViewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPersonActionPerformed(evt);
            }
        });

        btnCreateHomeAddress.setText("Create Home Address");
        btnCreateHomeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHomeAddressActionPerformed(evt);
            }
        });

        btnViewHomeAddress.setText("View Home Address");
        btnViewHomeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHomeAddressActionPerformed(evt);
            }
        });

        btnCreateLocalAddress.setText("Create Local Address");
        btnCreateLocalAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLocalAddressActionPerformed(evt);
            }
        });

        btnViewLocalAddress.setText("View Local Address");
        btnViewLocalAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLocalAddressActionPerformed(evt);
            }
        });

        btnCreateBankAccount.setText("Create Bank Account");
        btnCreateBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBankAccountActionPerformed(evt);
            }
        });

        btnViewBankAccount.setText("View Bank Account");
        btnViewBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBankAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonsLayout = new javax.swing.GroupLayout(panelButtons);
        panelButtons.setLayout(panelButtonsLayout);
        panelButtonsLayout.setHorizontalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreatePerson)
                    .addComponent(btnCreateHomeAddress)
                    .addComponent(btnViewHomeAddress)
                    .addComponent(btnViewPerson))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateLocalAddress)
                    .addComponent(btnViewLocalAddress)
                    .addComponent(btnCreateBankAccount)
                    .addComponent(btnViewBankAccount))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelButtonsLayout.setVerticalGroup(
            panelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewPerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateHomeAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewHomeAddress)
                .addGap(33, 33, 33)
                .addComponent(btnCreateLocalAddress)
                .addGap(18, 18, 18)
                .addComponent(btnViewLocalAddress)
                .addGap(33, 33, 33)
                .addComponent(btnCreateBankAccount)
                .addGap(18, 18, 18)
                .addComponent(btnViewBankAccount)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelButtons);

        javax.swing.GroupLayout panelDisplayLayout = new javax.swing.GroupLayout(panelDisplay);
        panelDisplay.setLayout(panelDisplayLayout);
        panelDisplayLayout.setHorizontalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        panelDisplayLayout.setVerticalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(panelDisplay);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
         CreatePersonJPanel panel = new CreatePersonJPanel(person);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnViewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPersonActionPerformed
        // TODO add your handling code here:
          ViewPersonJPane panel = new ViewPersonJPane(person);
          
          jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnViewPersonActionPerformed

    private void btnCreateHomeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHomeAddressActionPerformed
        // TODO add your handling code here:
         CreateHomeAddressJPanel panel = new CreateHomeAddressJPanel(homeAddress);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnCreateHomeAddressActionPerformed

    private void btnViewHomeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHomeAddressActionPerformed
        // TODO add your handling code here:
         ViewHomeAddressJPanel panel = new ViewHomeAddressJPanel(homeAddress);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnViewHomeAddressActionPerformed

    private void btnCreateLocalAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLocalAddressActionPerformed
        // TODO add your handling code here:
         CreateLocalAddressJPanel panel = new CreateLocalAddressJPanel(localAddress);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnCreateLocalAddressActionPerformed

    private void btnViewLocalAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLocalAddressActionPerformed
        // TODO add your handling code here:
        ViewLocalAddressJPanel panel = new ViewLocalAddressJPanel(localAddress);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnViewLocalAddressActionPerformed

    private void btnCreateBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBankAccountActionPerformed
        // TODO add your handling code here:
       CreateBankAccountJPanel panel = new CreateBankAccountJPanel(bankAccount);
        jSplitPane1.setRightComponent(panel);

    }//GEN-LAST:event_btnCreateBankAccountActionPerformed

    private void btnViewBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBankAccountActionPerformed
        // TODO add your handling code here:
         ViewBankAccountJPanel panel = new ViewBankAccountJPanel(bankAccount);
        jSplitPane1.setRightComponent(panel);
    }//GEN-LAST:event_btnViewBankAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateBankAccount;
    private javax.swing.JButton btnCreateHomeAddress;
    private javax.swing.JButton btnCreateLocalAddress;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JButton btnViewBankAccount;
    private javax.swing.JButton btnViewHomeAddress;
    private javax.swing.JButton btnViewLocalAddress;
    private javax.swing.JButton btnViewPerson;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelDisplay;
    // End of variables declaration//GEN-END:variables
}
