/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import model.BankAccount;

/**
 *
 * @author vedanarayananshrirangesh
 */
public class ViewBankAccountJPanel extends javax.swing.JPanel {
     BankAccount bankAccount;

    /**
     * Creates new form ViewBankAccountJPanel
     */
    public ViewBankAccountJPanel(BankAccount bankAccount) {
        this.bankAccount = bankAccount;
        initComponents();
        display();
        
    }
    private void display() {
        fieldBankName.setText(bankAccount.getBankName());
        fieldAccountNumbert.setText(bankAccount.getAccountNumber());
        fieldRoutingNumbert.setText(bankAccount.getRoutingNumber());
        fieldAccountTypet.setText(bankAccount.getAccountType());
        fieldAccountBalancet.setText(bankAccount.getBalance());

        
        fieldAccountNumbert.setEditable(false);
        fieldRoutingNumbert.setEditable(false);
        fieldAccountTypet.setEditable(false);
        fieldAccountBalancet.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldBankName = new javax.swing.JLabel();
        fieldAccountNum = new javax.swing.JLabel();
        fieldRoutingNum = new javax.swing.JLabel();
        fieldAccountType = new javax.swing.JLabel();
        fieldBalance = new javax.swing.JLabel();
        fieldAccountBankNamet = new javax.swing.JTextField();
        fieldAccountNumbert = new javax.swing.JTextField();
        fieldRoutingNumbert = new javax.swing.JTextField();
        fieldAccountTypet = new javax.swing.JTextField();
        fieldAccountBalancet = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        fieldBankName.setText("Bank Name");

        fieldAccountNum.setText("Account Number");

        fieldRoutingNum.setText("Routing Number");

        fieldAccountType.setText("Account Type");

        fieldBalance.setText("Balance");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(fieldAccountNum)
                                    .addGap(80, 80, 80))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fieldRoutingNum)
                                    .addGap(83, 83, 83)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fieldAccountType)
                                .addGap(97, 97, 97)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(fieldBalance)
                            .addGap(130, 130, 130))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldAccountBalancet, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(fieldAccountTypet, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(fieldRoutingNumbert)
                    .addComponent(fieldAccountNumbert)
                    .addComponent(fieldAccountBankNamet))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAccountBankNamet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAccountNum)
                            .addComponent(fieldAccountNumbert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldRoutingNum)
                            .addComponent(fieldRoutingNumbert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(fieldAccountType))
                    .addComponent(fieldAccountTypet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(fieldBalance))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(fieldAccountBalancet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAccountBalancet;
    private javax.swing.JTextField fieldAccountBankNamet;
    private javax.swing.JLabel fieldAccountNum;
    private javax.swing.JTextField fieldAccountNumbert;
    private javax.swing.JLabel fieldAccountType;
    private javax.swing.JTextField fieldAccountTypet;
    private javax.swing.JLabel fieldBalance;
    private javax.swing.JLabel fieldBankName;
    private javax.swing.JLabel fieldRoutingNum;
    private javax.swing.JTextField fieldRoutingNumbert;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
